// SPDX-License-Identifier: MIT

package com.daedalus.server.service;

import com.daedalus.engine.generators.*;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Campaign mode's two load-bearing promises (ADR-006 idea #10).
 *
 * <p><b>Determinism</b> — the same seed produces the same ladder anywhere, which is the whole
 * mechanism behind a shareable campaign link with no stored state.
 *
 * <p><b>The ladder actually climbs</b> — and it climbs because difficulty is <em>measured</em>
 * per candidate maze, not assumed from size. That distinction is the reason the theory module
 * exists in this feature, so it gets a real assertion: measured grades must rise across stages.
 */
class CampaignServiceTest {

    private MazeGenerationService gen;
    private GeneratorRegistry registry;
    private final java.util.List<Object> published = new java.util.ArrayList<>();

    @BeforeEach
    void setUp() {
        registry = new GeneratorRegistry(List.of(
                new BinaryTreeGenerator(), new SidewinderGenerator(), new PrimsGenerator(),
                new HuntAndKillGenerator(), new AldousBroderGenerator(),
                new RecursiveBacktrackerGenerator()));
        published.clear();
        gen = new MazeGenerationService(registry, published::add, new SimpleMeterRegistry());
    }

    private CampaignService service() {
        return new CampaignService(gen, registry, 6, 3, 9, 4, 50);
    }

    /**
     * Several seeds, not one. Asserting monotonicity on a single seed is how this test first
     * passed while the ladder walked backwards on 15 of 40 seeds. A 150-seed sweep during
     * development is strictly rising at this (default) config.
     *
     * <p><b>Why twenty and not five.</b> Five was the original compromise — enough to catch a
     * ladder that walks backwards on nearly half of all seeds, cheap enough not to slow the
     * suite. Mutation measured what it actually catches, and the answer was uncomfortable: the
     * two constants this class's javadoc records as load-bearing — the conservative target range
     * (raising it to the pool's ceiling collapsed monotonicity from 60/60 seeds to 34/60) and
     * the three-size candidate pool (a single size gave 25/40) — could both be reverted and all
     * five seeds still climbed. The only thing that failed was {@code DeterminismGoldenTest},
     * which notices that the bytes changed, not that the ladder stopped being one. A digest is
     * regenerated by whoever deliberately retunes a constant, so it would have waved both
     * regressions straight through. Twenty seeds costs about a second and fails on both.
     */
    @ParameterizedTest
    @ValueSource(longs = {1L, 2L, 3L, 5L, 7L, 11L, 13L, 17L, 19L, 23L,
                          42L, 99L, 123L, 777L, 1234L, 4242L, 31337L, 65537L, 99999L, 123456L})
    void theMeasuredDifficultyClimbsAcrossStages(long seed) {
        var campaign = service().campaign(seed);
        assertThat(campaign.stages()).hasSize(6);

        var scores = campaign.stages().stream()
                .map(s -> s.grade().score())
                .toList();
        for (int i = 1; i < scores.size(); i++) {
            assertThat(scores.get(i))
                    .as("seed %d: stage %d (%.2f) must measure harder than stage %d (%.2f) — a "
                            + "ladder whose rungs are not ordered is not a ladder",
                            seed, i, scores.get(i), i - 1, scores.get(i - 1))
                    .isGreaterThan(scores.get(i - 1));
        }
        // And it spans a real range, not six near-identical mazes (measured span is ~8+).
        assertThat(scores.get(scores.size() - 1) - scores.get(0)).isGreaterThan(4.0);
        assertThat(campaign.stages().get(0).grade().label()).isIn("gentle", "moderate");
        assertThat(campaign.stages().get(5).grade().label()).isIn("punishing", "brutal");
    }

    /**
     * Pins the "must clear the previous stage" selection rule, at a config where it is
     * load-bearing.
     *
     * <p>This test exists because the default config cannot pin it: measured across 60 seeds,
     * defaults are 60/60 monotone with the rule and 60/60 without it, so a default-config test
     * passes with the rule deleted — a guarantee in name only (verified by deleting it). At ten
     * stages the rungs crowd together and the rule becomes the whole story: 0/60 monotone
     * without it, 53/60 with. These seeds are among the ones it rescues.
     */
    @ParameterizedTest
    @ValueSource(longs = {1L, 2L})
    void theClearThePreviousRuleIsWhatOrdersLongerLadders(long seed) {
        var campaign = new CampaignService(gen, registry, 10, 2, 9, 3, 50).campaign(seed);
        var scores = campaign.stages().stream().map(s -> s.grade().score()).toList();
        for (int i = 1; i < scores.size(); i++) {
            assertThat(scores.get(i))
                    .as("seed %d: stage %d (%.2f) vs %d (%.2f) — without the clear-the-previous "
                            + "rule this ten-stage ladder is non-monotone on every seed measured",
                            seed, i, scores.get(i), i - 1, scores.get(i - 1))
                    .isGreaterThan(scores.get(i - 1));
        }
    }

    @Test
    void theSameSeedPlansTheSameCampaignAnywhere() {
        // A second service instance with a fresh maze cache stands in for another replica.
        var first = service().campaign(99L);
        var other = new MazeGenerationService(new GeneratorRegistry(List.of(
                new BinaryTreeGenerator(), new SidewinderGenerator(), new PrimsGenerator(),
                new HuntAndKillGenerator(), new AldousBroderGenerator(),
                new RecursiveBacktrackerGenerator())), event -> { }, new SimpleMeterRegistry());
        var second = new CampaignService(other, registry, 6, 3, 9, 4, 50).campaign(99L);

        for (int i = 0; i < first.stages().size(); i++) {
            var a = first.stages().get(i);
            var b = second.stages().get(i);
            assertThat(b.seed()).as("stage %d chose a different maze seed", i).isEqualTo(a.seed());
            assertThat(b.generatorId()).isEqualTo(a.generatorId());
            assertThat(b.rows()).isEqualTo(a.rows());
            assertThat(b.grade().score()).isEqualTo(a.grade().score());
            // Same seed + same generator ⇒ same topology (ids differ; they are per-instance).
            assertThat(other.find(b.mazeId()).grid().toTileGrid())
                    .isDeepEqualTo(gen.find(a.mazeId()).grid().toTileGrid());
        }
        assertThat(second.stages().get(0).mazeId()).isNotEqualTo(first.stages().get(0).mazeId());
    }

    @Test
    void stageMazeIdsAreStableSoLeaderboardsAndGhostsCompose() {
        var svc = service();
        var first = svc.campaign(7L);
        var again = svc.campaign(7L);
        // Stable ids are what make per-maze leaderboards and ghosts work per stage: they key
        // off the maze id, so a wobbling id would silently reset a stage's board every request.
        assertThat(again.stages().stream().map(CampaignService.Stage::mazeId).toList())
                .isEqualTo(first.stages().stream().map(CampaignService.Stage::mazeId).toList());
        assertThat(svc.stage(7L, 3).mazeId()).isEqualTo(first.stages().get(3).mazeId());
        assertThat(svc.stage(7L, 99)).isNull();
        assertThat(svc.stage(7L, -1)).isNull();
    }

    /**
     * Planning must not leak its rejected candidates into the world.
     *
     * <p>The first implementation graded candidates by generating them through
     * {@link MazeGenerationService#generate}, which caches every maze and announces it. A
     * 6-stage campaign evaluates 54 candidates and serves 6, so 89% of them were caching into
     * a bounded store — evicting mazes real users were playing — and firing
     * {@code MazeGeneratedEvent} at every plugin and STOMP subscriber for mazes nobody could
     * fetch. Nothing in the campaign response showed it, which is exactly why it needs a test.
     */
    @Test
    void planningDoesNotCacheOrAnnounceTheCandidatesItRejects() {
        var campaign = service().campaign(31337L);

        var generated = published.stream()
                .filter(com.daedalus.plugin.events.MazeGeneratedEvent.class::isInstance)
                .map(com.daedalus.plugin.events.MazeGeneratedEvent.class::cast)
                .map(e -> e.metadata().id())
                .toList();
        var servedIds = campaign.stages().stream().map(CampaignService.Stage::mazeId).toList();

        assertThat(generated)
                .as("exactly one announced maze per stage — one event per candidate means "
                        + "plugins and subscribers are told about mazes that are never served")
                .containsExactlyInAnyOrderElementsOf(servedIds);
        // And nothing beyond the served stages is resident in the cache.
        assertThat(generated).hasSize(campaign.stages().size());
        for (var id : servedIds) {
            assertThat(gen.find(id)).as("a served stage must be fetchable").isNotNull();
        }
    }

    @Test
    void hazardsRampInOverTheBackHalfAndAreOnlyDeclared() {
        var campaign = service().campaign(5L);
        // The whole ramp, rung by rung. Checking only the first and last stage says "hazards
        // start empty and end full", which is also true of a ramp that dumps everything at the
        // half-way mark — and mutation confirmed that collapsing the traffic threshold from
        // 0.75 to 0.5 of the ladder passed every assertion this test used to make.
        assertThat(campaign.stages().get(0).hazards()).isEmpty();
        assertThat(campaign.stages().get(1).hazards()).isEmpty();
        assertThat(campaign.stages().get(2).hazards()).isEmpty();
        assertThat(campaign.stages().get(3).hazards()).containsExactly("living");
        assertThat(campaign.stages().get(4).hazards())
                .as("traffic arrives at three quarters, one rung after living — a ramp that "
                        + "arrives all at once is a difficulty cliff, not a ramp")
                .containsExactly("living");
        assertThat(campaign.stages().get(5).hazards())
                .as("hardening is the finale only — ADR-008's composition, not a second "
                        + "living ticker. A second /live would join the existing run and "
                        + "drop ?seal=")
                .containsExactly("living", "traffic", "hardening");
        // Declared, never started: planning a campaign must not mutate any maze. A living
        // ticker would have eroded stage 5's grid; its topology still matches its seed.
        var stage = campaign.stages().get(5);
        var replayed = gen.generate(stage.generatorId(), stage.rows(), stage.cols(), stage.seed());
        assertThat(gen.find(stage.mazeId()).grid().toTileGrid())
                .as("planning a campaign started a hazard ticker — stages must be inert")
                .isDeepEqualTo(replayed.grid().toTileGrid());
    }

    @Test
    void theCampaignPlanMapIsBounded() {
        // House rule: bounded everywhere. Nothing checked this one, and nothing would have —
        // an unbounded plan map does not fail, it just keeps every campaign anyone ever linked.
        var svc = new CampaignService(gen, registry, 3, 2, 9, 4, 4);
        for (long seed = 1; seed <= 20; seed++) {
            svc.campaign(seed);
            assertThat(svc.plannedCount())
                    .as("after %d distinct campaigns", seed)
                    .isLessThanOrEqualTo(4);
        }
        // And the bound costs nothing but recomputation: an evicted plan replays identically.
        assertThat(svc.campaign(1L).stages().stream().map(CampaignService.Stage::seed).toList())
                .isEqualTo(svc.campaign(1L).stages().stream()
                        .map(CampaignService.Stage::seed).toList());
    }

    @Test
    void aCampaignWhoseStageMazesWereEvictedIsReplannedRatherThanServedStale() {
        var evicting = new ScriptedGen(registry, published::add);
        var svc = new CampaignService(evicting, registry, 3, 2, 9, 4, 50);
        var first = svc.campaign(11L);

        // The maze cache is bounded and idle-expiring; a campaign link outlives it easily.
        evicting.hidden.add(first.stages().get(1).mazeId());
        var again = svc.campaign(11L);

        assertThat(again.stages().get(1).mazeId())
                .as("a plan holding an id the cache has dropped serves a 404 for a stage the "
                        + "campaign says exists — replan instead")
                .isNotEqualTo(first.stages().get(1).mazeId());
        assertThat(evicting.find(again.stages().get(1).mazeId())).isNotNull();
        assertThat(again.stages().stream().map(CampaignService.Stage::seed).toList())
                .as("replanning is regeneration from the same seeds, not a different campaign")
                .isEqualTo(first.stages().stream().map(CampaignService.Stage::seed).toList());
    }
}
