// SPDX-License-Identifier: MIT

package com.daedalus.server;

import com.daedalus.server.config.ProdSecurityConfig;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.client.RestTestClient;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Pins that the static web UI is actually served. The page is plain static
 * content under {@code resources/static}, which Boot serves by convention —
 * and conventions are exactly what starter upgrades silently change.
 *
 * <p><b>This is a boot-and-serve contract, not a leftover-state mirror.</b>
 * Leftover-state and feature regressions belong in {@code sweep/}:
 * {@code api-sweep.py} runs in CI; {@code ui-sweep.js} is the local Playwright
 * pass. Do not add {@code indexOf("async function …")} body pins here.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class WebUiSmokeTest {

    @LocalServerPort
    private int port;

    @Test
    void theWebUiIsServedAtTheRoot() {
        RestTestClient client = RestTestClient.bindToServer()
                .baseUrl("http://localhost:" + port).build();
        byte[] body = client.get().uri("/index.html").exchange()
                .expectStatus().isOk()
                .expectBody().returnResult().getResponseBody();
        assertThat(body).isNotNull();
        StringBuilder js = new StringBuilder();
        for (String path : ProdSecurityConfig.STATIC_SCRIPTS) {
            byte[] bytes = client.get().uri(path).exchange()
                    .expectStatus().isOk()
                    .expectBody().returnResult().getResponseBody();
            assertThat(bytes).as("nothing served at %s", path).isNotNull();
            js.append(new String(bytes));
        }
        String html = new String(body) + js;
        // Public surface, not leftover names. Paths, ids, permalink kinds, and
        // refuse copy are what a player or operator sees. Function names belong
        // in sweep/ — a rename there must not fail this boot-and-serve test.
        assertThat(html).contains("DAEDALUS").contains("id=\"gate\"").contains("id=\"gateWell\"")
                .contains("id=\"gateExploreCmd\"").contains("id=\"home\"")
                .contains("gate-brand").contains("gate-veil").contains("Other hosts")
                .contains("text-indent: .22em; color: #f2ead8; user-select: none; -webkit-user-select: none")
                .contains("-webkit-tap-highlight-color: transparent; -webkit-touch-callout: none; -webkit-user-drag: none; cursor: default")
                .contains("text-transform: uppercase; color: #b09a72; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none")
                .contains("color: #b09a72; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("color: #b09a72; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; -webkit-user-drag: none; cursor: default")
                .contains("-webkit-tap-highlight-color: transparent; -webkit-touch-callout: none")
                .contains("-webkit-user-select: none; -webkit-tap-highlight-color: transparent; -webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\"")
                .contains("name=\"theme-color\" content=\"#0c0908\"")
                .contains("name=\"theme-color\" content=\"#0c0908\" media=\"(prefers-color-scheme: light)\"")
                .contains("name=\"msapplication-TileColor\" content=\"#0c0908\"")
                .contains("name=\"msapplication-navbutton-color\" content=\"#0c0908\"")
                .contains("name=\"msapplication-TileImage\" content=\"data:image/png;base64,")
                .contains("name=\"mobile-web-app-capable\" content=\"yes\"")
                .contains("name=\"apple-mobile-web-app-capable\" content=\"yes\"")
                .contains("name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\"")
                .contains("name=\"color-scheme\" content=\"dark\"")
                .contains("name=\"format-detection\" content=\"telephone=no\"")
                .contains("rel=\"icon\" type=\"image/svg+xml\"")
                .contains("fill='%230c0908'")
                .contains("stroke='%23b88538'")
                .contains("rel=\"mask-icon\" color=\"#b88538\"")
                .contains("fill-rule='evenodd' d='M0 0h32v32H0zM1 1h30v30H1z'")
                .contains("rel=\"apple-touch-icon\"")
                .contains("rel=\"apple-touch-startup-image\"")
                .contains("property=\"og:image\"")
                .contains("name=\"twitter:image\"")
                .contains("rel=\"manifest\" href=\"data:application/manifest+json,")
                .contains("%22background_color%22%3A%22%230c0908%22")
                .contains("%22theme_color%22%3A%22%230c0908%22")
                .contains("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2j")
                .contains("color: #f2ead8")
                .contains("header h1 button")
                .contains("padding-top: calc(10px + env(safe-area-inset-top, 0px));")
                .contains("padding-left: calc(22px + env(safe-area-inset-left, 0px));")
                .contains("padding-right: calc(22px + env(safe-area-inset-right, 0px));")
                .contains("all: unset; cursor: pointer; letter-spacing: .22em;")
                .contains("-webkit-tap-highlight-color: transparent; -webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("color: #f2ead8; user-select: none; -webkit-user-select: none")
                .contains("-webkit-tap-highlight-color: transparent; -webkit-touch-callout: none")
                .contains("header .tag { color: #b09a72")
                .contains("text-transform: lowercase; text-wrap: pretty; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none")
                .contains("text-wrap: pretty; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("pretty; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; -webkit-user-drag: none; cursor: default")
                .contains("rgba(22, 18, 14, .88)")
                .contains("rgba(22, 18, 14, .88); cursor: default")
                .contains("rgba(22, 18, 14, .88); cursor: default; -webkit-user-drag: none")
                .contains("#gate { position: fixed; inset: 0; z-index: 20; overflow: auto; overscroll-behavior: none;")
                .contains("overflow: auto; overscroll-behavior: none; cursor: default")
                .contains("overflow: auto; overscroll-behavior: none; cursor: default; -webkit-user-drag: none")
                .contains("padding-top: calc(48px + env(safe-area-inset-top, 0px));")
                .contains("padding-bottom: calc(56px + env(safe-area-inset-bottom, 0px));")
                .contains("padding-left: calc(20px + env(safe-area-inset-left, 0px));")
                .contains("padding-right: calc(20px + env(safe-area-inset-right, 0px));")
                .contains("padding-bottom: calc(28px + env(safe-area-inset-bottom, 0px));")
                .contains("align-items: start; -webkit-user-drag: none")
                .contains("12px; color: var(--accent); -webkit-user-drag: none")
                .contains("gap: 6px; margin-left: auto; -webkit-user-drag: none")
                .contains("html, body { min-height: 100%; color-scheme: dark; background-color: #0c0908;")
                .contains("color-scheme: dark; background-color: #0c0908; cursor: default")
                .contains("color-scheme: dark; background-color: #0c0908; cursor: default; -webkit-user-drag: none")
                .contains("overscroll-behavior: none;")
                .contains("-webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;")
                .contains("text-rendering: optimizeLegibility;")
                .contains("font-synthesis: none;")
                .contains("text-size-adjust: 100%; -webkit-text-size-adjust: 100%;")
                .contains("-webkit-tap-highlight-color: rgba(153, 111, 49, 0.25);")
                .contains("touch-action: manipulation;")
                .contains("::-webkit-scrollbar { width: 8px; height: 8px; }")
                .contains("::-webkit-scrollbar-thumb { background: rgba(153, 111, 49, 0.45); border-radius: 4px; }")
                .contains("::-webkit-scrollbar-thumb:hover { background: rgba(153, 111, 49, 0.65); }")
                .contains("::-webkit-scrollbar-thumb:active { background: rgba(153, 111, 49, 0.85); }")
                .contains("::-webkit-scrollbar-track { background: transparent; }")
                .contains("::-webkit-scrollbar-corner { background: transparent; }")
                .contains("::-webkit-scrollbar-button { display: none; width: 0; height: 0; }")
                .contains("::selection { background: rgba(153, 111, 49, 0.35); color: #f2ead8; }")
                .contains("::-moz-selection { background: rgba(153, 111, 49, 0.35); color: #f2ead8; }")
                .contains("::target-text { background: rgba(153, 111, 49, 0.35); color: #f2ead8; }")
                .contains("::search-text { background: rgba(153, 111, 49, 0.35); color: #f2ead8; }")
                .contains("::search-text:current { background: rgba(153, 111, 49, 0.55); color: #f2ead8; }")
                .contains("::highlight { background: rgba(153, 111, 49, 0.35); color: #f2ead8; }")
                .contains("::selection:window-inactive { background: rgba(153, 111, 49, 0.22); color: #f2ead8; }")
                .contains("::-moz-selection:window-inactive { background: rgba(153, 111, 49, 0.22); color: #f2ead8; }")
                .contains("@media print {")
                .contains("print-color-adjust: exact; -webkit-print-color-adjust: exact;")
                .contains("@page { background-color: #0c0908; color: #f2ead8; }")
                .contains("@media (forced-colors: active) {")
                .contains("html, body, #gate, #stage, canvas { forced-color-adjust: none; }")
                .contains("mark { background: rgba(153, 111, 49, 0.35); color: #f2ead8;")
                .contains("::spelling-error { text-decoration: underline wavy rgba(153, 111, 49, 0.85); }")
                .contains("::grammar-error { text-decoration: underline wavy rgba(176, 154, 114, 0.85); }")
                .contains("#gate article h3")
                .contains("letter-spacing: .04em; color: #f2ead8; cursor: default")
                .contains("color: #f2ead8; cursor: default; -webkit-touch-callout: none")
                .contains("color: #f2ead8; cursor: default; -webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("letter-spacing: .04em; color: #f2ead8")
                .contains("#gate .lede { color: #b09a72")
                .contains("max-width: 40rem; cursor: default")
                .contains("max-width: 40rem; cursor: default; -webkit-user-drag: none")
                .contains("max-width: 980px; margin: 0 auto; -webkit-user-drag: none")
                .contains("gap: 12px; -webkit-user-drag: none")
                .contains("color: #b09a72; cursor: text; margin: 0 0 22px")
                .contains("text-wrap: pretty; animation: gateRise .7s .1s ease both;")
                .contains("#gate article p { margin: 0; color: #b09a72")
                .contains("#gate article { background: rgba(22, 18, 14, .88); cursor: default; -webkit-user-drag: none;\n"
                        + "                  border: 1px solid rgba(153, 111, 49, 0.28);")
                .contains("color: #b09a72; cursor: text; font-size: 13px")
                .contains("font-size: 13px; flex: 1;")
                .contains("text-wrap: pretty;")
                .contains("animation: gateRise .55s ease both, panelRimBreath 4.5s ease-in-out infinite")
                .contains("#gate pre { margin: 0; padding: 8px; background: #16120e; color: #afa088;")
                .contains("#gate pre { margin: 0; padding: 8px; background: #16120e; color: #afa088; cursor: text;\n"
                        + "              border: 1px solid rgba(153, 111, 49, 0.28);")
                .contains("background: #16120e; color: #afa088; cursor: text")
                .contains("font: 11px/1.45 ui-monospace, monospace; overflow: auto; overscroll-behavior: none;")
                .contains("gateBreath").contains("gateVeil")
                .contains("rgba(245, 193, 74, .05)")
                .contains("rgba(184, 133, 56, 0.28)")
                .contains("/api/v1").contains("/ws")
                .contains("/auth/login").contains("id=\"login\"").contains("id=\"fog\"")
                .contains("id=\"legend\"").contains("id=\"labMetric\"").contains("class=\"rail\"")
                .contains("id=\"compareBox\"")
                .contains("#compareBox tr.solver-row:hover { background: #1a1610")
                .contains("#compareBox tr.pinned { background: #1a1610")
                .contains("#compareBox { max-height: 22vh")
                .contains("scrollbar-color: rgba(184, 133, 56, 0.45) transparent")
                .contains("color: #f2ead8")
                .contains("#compareBox th { text-align: left; color: #b09a72")
                .contains("#compareBox th { text-align: left; color: #b09a72; font-weight: 600; -webkit-user-drag: none")
                .contains("font-weight: 600; -webkit-user-drag: none;\n"
                        + "                   border-bottom: 1px solid rgba(153, 111, 49, 0.28); padding: 2px 8px;")
                .contains("#compareBox td { padding: 2px 8px; border-bottom: 1px solid rgba(153, 111, 49, 0.28)")
                .contains("#compareBox td { padding: 2px 8px; border-bottom: 1px solid rgba(153, 111, 49, 0.28); -webkit-user-drag: none")
                .contains("#compareBox .hint { color: #b09a72")
                .contains("#compareBox > div { border-top: 1px solid rgba(153, 111, 49, 0.28); padding-top: 6px;")
                .contains("#compareBox > div { border-top: 1px solid rgba(153, 111, 49, 0.28); padding-top: 6px; -webkit-user-drag: none")
                .contains("#compareBox .best { color: #c49425")
                .contains("color:#c49425\">${escapeHtml(w.id)}</b> wins the arena")
                .contains("color:#c49425\">${escapeHtml(w.id)}</b> wins by default")
                .contains("id=\"genInfo\"").contains("id=\"asciiOut\"")
                .contains("#asciiOut { margin: 10px 0 0; padding: 8px; background: #16120e;")
                .contains("background: radial-gradient(circle at 50% 35%, #16120e 38%, #0c0908);\n"
                        + "              border: 1px solid rgba(153, 111, 49, 0.28); border-radius: 6px;")
                .contains("#log, #lb, #stats, #asciiOut, #gate pre, #tourBox, #labOut,")
                .contains("#status, #compareBox, #pluginBox, #worldBox, #campaignBox {")
                .contains("#worldBox div { border-bottom: 1px solid rgba(153, 111, 49, 0.28); padding: 2px 0;")
                .contains("#worldBox { color: #b09a72; padding: 8px; background: #16120e;\n"
                        + "              border: 1px solid rgba(153, 111, 49, 0.28); border-radius: 6px;")
                .contains("font-variant-numeric: tabular-nums;")
                .contains("var(--panel); cursor: default;")
                .contains("var(--panel); cursor: default; -webkit-user-drag: none")
                .contains("details .hint { cursor: text; }")
                .contains("font: 11px/1.2 ui-monospace, monospace; overflow: auto; overscroll-behavior: none;")
                .contains("animation: panelRimBreath 4.5s ease-in-out infinite; }")
                .contains("0%, 100% { border-color: rgba(153, 111, 49, 0.30); }")
                .contains(".exports button, .exports a, #asciiOut, #gate pre, .info, #stats, details,")
                .contains("#compareBox > div, kbd, summary::after, #log, #lb, #pluginBox, #campaignBox,")
                .contains("#tourBox, #labOut, #compareBox, #status {")
                .contains("#campaignBox { padding: 8px; background: #16120e;")
                .contains("#campaignBox { padding: 8px; background: #16120e;\n"
                        + "                 border: 1px solid rgba(153, 111, 49, 0.28); border-radius: 6px;")
                .contains("#tourBox { padding: 8px; background: #16120e;")
                .contains("#tourBox { padding: 8px; background: #16120e;\n"
                        + "             border: 1px solid rgba(153, 111, 49, 0.28); border-radius: 6px;")
                .contains("#labOut { padding: 8px; background: #16120e;")
                .contains("#labOut { padding: 8px; background: #16120e;\n"
                        + "            border: 1px solid rgba(153, 111, 49, 0.28); border-radius: 6px;")
                .contains("#compareBox { max-height: 22vh; overflow: auto; overscroll-behavior: none; min-width: 0;")
                .contains("color: #f2ead8; cursor: text; padding: 8px; background: #16120e;\n"
                        + "                border: 1px solid rgba(153, 111, 49, 0.28); border-radius: 6px;")
                .contains("color: #f2ead8; cursor: text; padding: 8px")
                .contains("animation: chevronBreath 4.5s ease-in-out infinite; }")
                .contains("animation: infoRimBreath 4.5s ease-in-out infinite; }")
                .contains("margin-top: 8px; -webkit-user-drag: none;")
                .contains("border-left: 2px solid rgba(153, 111, 49, 0.28); padding-left: 8px;")
                .contains("0%, 100% { border-left-color: rgba(153, 111, 49, 0.28); }")
                .contains("animation: statsRimBreath 4.5s ease-in-out infinite; }")
                .contains("0%, 100% { border-top-color: rgba(153, 111, 49, 0.28); }")
                .contains("color: #afa088;")
                .contains("max-height: 22vh; color: #afa088")
                .contains("max-height: 22vh; color: #afa088; cursor: text")
                .contains("#asciiOut .rock { color: #766442")
                .contains("#asciiOut .gate { color: #3ab675")
                .contains("#asciiOut .exit { color: #d04e4f")
                .contains("replace(/#/g, \"<span class=\\\"rock\\\">#</span>\")")
                .contains("replace(/S/g, \"<span class=\\\"gate\\\">S</span>\")")
                .contains("replace(/G/g, \"<span class=\\\"exit\\\">G</span>\")")
                .contains("scrollbar-width: thin; scrollbar-color: rgba(184, 133, 56, 0.45) transparent; }")
                .contains("class=\"exports\"").contains("EXPORT_RESERVE")
                .contains("canvas { background: transparent; display: block;")
                .contains("image-rendering: crisp-edges; image-rendering: pixelated;")
                .contains("user-select: none; -webkit-user-select: none; -webkit-touch-callout: none;")
                .contains("-webkit-user-drag: none;")
                .contains("-webkit-user-drag: none; cursor: default; touch-action: none")
                .contains("-webkit-tap-highlight-color: transparent; outline: none")
                .contains("id=\"pngExport\" class=\"hint\" href=\"#\" download=\"maze.png\"")
                .contains(".exports a:focus-visible { outline: 2px solid rgba(153, 111, 49, 0.85); outline-offset: 1px; }")
                .contains(".exports button, .exports a, .exports a:visited, .exports a:active { width: auto")
                .contains("letter-spacing: .03em; color: #b09a72; text-decoration: none")
                .contains("style=\"display:none\">download as PNG")
                .contains("color: #b09a72")
                .contains("background: rgba(16, 11, 8, .78)")
                .contains("Pick a generator and press Generate")
                .contains("Bahnschrift")
                .contains("radial-gradient(80% 70% at 50% 45%")
                .contains("inset 0 0 48px rgba(0, 0, 0, .35)")
                .contains("rgba(184, 133, 56")
                .contains("0 0 18px rgba(62, 224, 143")
                .contains("animation: gateBreath 4.5s ease-in-out infinite")
                .contains("board-panel")
                .contains("gap: 12px; min-width: 0; -webkit-user-drag: none")
                .contains(".board-panel { display: flex; flex-direction: column; min-height: calc(100vh - 88px);")
                .contains("min-height: calc(100vh - 88px); cursor: default")
                .contains("min-height: calc(100vh - 88px); cursor: default; -webkit-user-drag: none")
                .contains("background: #16120e;")
                .contains("0 0 0 1px rgba(16, 11, 8, 0.85)")
                .contains("inset 3px 0 0 rgba(153, 111, 49, 0.95)")
                .contains("inset 3px 0 0 rgba(153, 111, 49, 0.55)")
                .contains("0 0 12px rgba(184, 133, 56")
                .contains("outline: 2px solid rgba(184, 133, 56")
                .contains("border: 1px solid rgba(184, 133, 56, 0.28)")
                .contains("border: 1px solid rgba(184, 133, 56, 0.32)")
                .contains("border: 1px solid rgba(153, 111, 49, 0.36)")
                .contains("button.accent")
                .contains("border-color: var(--gold)")
                .contains("backdrop-filter")
                .contains("floorWarm")
                .contains("g.fillStyle = emptyWordmarkInk()")
                .contains("wallWarm")
                .contains("0.22 * edge")
                .contains("floor: \"#40403c\"")
                .contains("mixHex(COLORS.floor, COLORS.floorWarm, 0.28)")
                .contains("radial-gradient(circle at 45% 40%, #484339 28%, #2a2218)")
                .contains("mixHex(warm, COLORS.floorDim, 0.22 * edge)")
                .contains("mixHex(hi, COLORS.floorDim, 0.22 * edge)")
                .contains("floorDim: \"#2a2218\"")
                .contains("mixHex(COLORS.floorHi, COLORS.floorWarm, lamp * 0.28)")
                .contains("floorHi: \"#765834\"")
                .contains("wallHi: \"#4a3824\"")
                .contains("mixHex(COLORS.wallHi, COLORS.wallWarm, 0.28)")
                .contains("paintWallHi(g, geom, r, c, mixHex(COLORS.wallHi, COLORS.wallWarm, 0.28))")
                .contains("wall: \"#120e0c\"")
                .contains("mixHex(COLORS.wall, COLORS.wallWarm, 0.28)")
                .contains("radial-gradient(circle at 45% 40%, #19140f 28%, #15110d)")
                .contains("scene.fog")
                .contains("COLORS.unseen")
                .contains("unseen: \"#0c0908\"")
                .contains("<span data-key=\"fog\"><i></i>unseen (fog)</span>")
                .contains("g.fillStyle = fogWash")
                .contains("mixHex(warmWall, COLORS.unseen, 0.28 * edge)")
                .contains("FOG_FRONTIER")
                .contains("fogFrontier")
                .contains("FOG_FRONTIER_BREATH_MS")
                .contains("0.92 + 0.16")
                .contains("core + geom.cell * (0.18 + 0.05")
                .contains("geom.cell * (0.28 + 0.04")
                .contains("ENDPOINT_BREATH_MS")
                .contains("0.55 + 0.06")
                .contains("shadowBlur")
                .contains("EMPTY_BREATH_MS")
                .contains("mixHex(\"#16120e\", \"#1a1510\", wave)")
                .contains("voidWash.addColorStop(1, COLORS.unseen)")
                .contains("0.36 + 0.10")
                .contains("0.22 + 0.08")
                .contains("0.72 + 0.18")
                .contains("0.55 + 0.20")
                .contains("0.08 + 0.04")
                .contains("0.04 + 0.03")
                .contains("prefers-reduced-motion")
                .contains("stageRimBreath")
                .contains("animation: stageRimBreath 4.5s ease-in-out infinite")
                .contains("-webkit-tap-highlight-color: transparent; outline: none; -webkit-touch-callout: none")
                .contains("outline: none; -webkit-touch-callout: none; user-select: none; -webkit-user-select: none")
                .contains("user-select: none; -webkit-user-select: none; -webkit-user-drag: none")
                .contains("user-select: none; -webkit-user-select: none; -webkit-user-drag: none; cursor: default")
                .contains("#1a1510 0%")
                .contains("#16120e 0%")
                .contains("radial-gradient(1200px 700px at 50% -10%, #16120e 0%")
                .contains("font: 14px/1.5 system-ui, \"Segoe UI\", sans-serif")
                .doesNotContain("color: var(--text);\r\n         font: 14px/1.5")
                .contains("#1a1510 0%")
                .contains("--void: #0c0908")
                .contains("--bg: #0c0908")
                .contains("--panel: #16120e")
                .doesNotContain("--panel: #10151b")
                .doesNotContain("--accent2: #7eb6ff")
                .contains("--accent2: #8fb8ff")
                .doesNotContain("--line: #1e2832")
                .contains("--line: #2a2218")
                .contains(".panel h2 { margin: 0 0 8px; font-size: 11px; text-transform: uppercase;")
                .contains("letter-spacing: .14em; color: #b09a72; font-weight: 600; user-select: none")
                .contains("font-weight: 600; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none")
                .contains("font-weight: 600; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("600; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; -webkit-user-drag: none; cursor: default")
                .contains(".hint { font-size: 11px; color: #b09a72; margin-top: 10px; }")
                .contains("#log { height: 240px; overflow-y: auto; overscroll-behavior: none; font: 12px/1.6 ui-monospace, monospace;")
                .contains("color: #f2ead8; padding: 8px; background: #16120e;\n"
                        + "         border: 1px solid rgba(153, 111, 49, 0.28); border-radius: 6px;")
                .contains("color: #f2ead8;")
                .contains("#log .t { color: #b09a72; margin-right: 6px;")
                .contains("#log .solver { color: #d4a04c;")
                .contains("#log div { border-bottom: 1px solid rgba(153, 111, 49, 0.28); padding: 2px 0;")
                .contains("padding: 2px 0; -webkit-user-drag: none")
                .contains("#labOut, #tourBox, #campaignBox { color: #f2ead8; }")
                .contains("overflow-wrap: break-word; hyphens: none; line-height: 1.5;")
                .contains("#pluginBox { color: #b09a72; padding: 8px; background: #16120e;")
                .contains("#pluginBox { color: #b09a72; padding: 8px; background: #16120e;\n"
                        + "               border: 1px solid rgba(153, 111, 49, 0.28); border-radius: 6px;")
                .contains("#pluginBox b { color: #f2ead8;")
                .contains("#tourBox table { width: 100%; border-collapse: collapse; -webkit-user-drag: none")
                .contains("#tourBox th { text-align: left; color: #b09a72; font-weight: 600;")
                .contains("#tourBox th { text-align: left; color: #b09a72; font-weight: 600; -webkit-user-drag: none")
                .contains("font-weight: 600; -webkit-user-drag: none;\n"
                        + "                border-bottom: 1px solid rgba(153, 111, 49, 0.28); padding: 2px 8px;")
                .contains("#tourBox td { padding: 2px 8px; border-bottom: 1px solid rgba(153, 111, 49, 0.28);")
                .contains("#tourBox td { padding: 2px 8px; border-bottom: 1px solid rgba(153, 111, 49, 0.28); -webkit-user-drag: none")
                .contains("#tourBox a, #tourBox a:visited, #tourBox a:active { color: #d4a04c; text-decoration: none; }")
                .contains("#tourBox a:focus-visible { outline: 2px solid rgba(153, 111, 49, 0.85); outline-offset: 1px; }")
                .contains("#labOut table { width: 100%; border-collapse: collapse; -webkit-user-drag: none")
                .contains("#labOut th { text-align: left; color: #b09a72; font-weight: 600;")
                .contains("#labOut th { text-align: left; color: #b09a72; font-weight: 600; -webkit-user-drag: none")
                .contains("font-weight: 600; -webkit-user-drag: none;\n"
                        + "               border-bottom: 1px solid rgba(153, 111, 49, 0.28); padding: 2px 8px;")
                .contains("#labOut td { padding: 2px 8px; border-bottom: 1px solid rgba(153, 111, 49, 0.28);")
                .contains("#labOut td { padding: 2px 8px; border-bottom: 1px solid rgba(153, 111, 49, 0.28); -webkit-user-drag: none")
                .contains("#pluginBox .rank { color: #b09a72;")
                .contains("#pluginBox div { border-bottom: 1px solid rgba(153, 111, 49, 0.28); padding: 2px 0;")
                .contains("#pluginBox div { border-bottom: 1px solid rgba(153, 111, 49, 0.28); padding: 2px 0; -webkit-user-drag: none")
                .contains("#campaignBox div { border-bottom: 1px solid rgba(153, 111, 49, 0.28);")
                .contains("#campaignBox div { border-bottom: 1px solid rgba(153, 111, 49, 0.28); -webkit-user-drag: none")
                .contains("#campaignBox a, #campaignBox a:visited, #campaignBox a:active { color: #d4a04c; text-decoration: none; }")
                .contains("#campaignBox a:focus-visible { outline: 2px solid rgba(153, 111, 49, 0.85); outline-offset: 1px; }")
                .contains("const LAB_SERIES = \"#af8441\"")
                .contains("stroke=\"#766442\" stroke-width=\"2\"")
                .contains("stroke=\"#16120e\" stroke-width=\"2\"")
                .contains("stroke=\"rgba(153, 111, 49, 0.28)\"")
                .contains("fill=\"#b09a72\" font-size=\"9\"")
                .contains("#lb { font: 12px/1.9 ui-monospace, monospace; color: #f2ead8;")
                .contains("#lb { font: 12px/1.9 ui-monospace, monospace; color: #f2ead8;\n"
                        + "        padding: 8px; background: #16120e;\n"
                        + "        border: 1px solid rgba(153, 111, 49, 0.28); border-radius: 6px;")
                .contains("#lb div { border-bottom: 1px solid rgba(153, 111, 49, 0.28); padding: 2px 0;")
                .contains("#lb div { border-bottom: 1px solid rgba(153, 111, 49, 0.28); padding: 2px 0; -webkit-user-drag: none")
                .contains("#lb span { color: #b09a72;")
                .contains("#lb .rank { display: inline-block; width: 18px; color: #b09a72;")
                .contains("#lb b { color: #f2ead8;")
                .contains("${active ? \"background:#1a1610;\" : \"\"}")
                .contains("color:${done ? \"#4cc38a\" : \"#d4a04c\"}")
                .contains("details { margin-top: 10px; border-top: 1px solid rgba(153, 111, 49, 0.28); padding-top: 6px;")
                .contains("0.28); padding-top: 6px; -webkit-user-drag: none")
                .contains("letter-spacing: .12em; color: #b09a72; margin: 4px 0 2px; user-select: none")
                .contains("margin: 4px 0 2px; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none")
                .contains("margin: 4px 0 2px; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("summary::after { content: \" ▸\"; color: rgba(153, 111, 49, 0.55);")
                .contains("kbd { background: #16120e; border: 1px solid rgba(153, 111, 49, 0.28); border-radius: 3px;")
                .contains("padding: 0 4px; font-size: 11px; color: #b09a72; user-select: none")
                .contains("font-size: 11px; color: #b09a72; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none")
                .contains("font-size: 11px; color: #b09a72; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("4px; font-size: 11px; color: #b09a72; user-select: none; -webkit-user-select: none")
                .contains("background: rgba(12, 9, 8, 0.92)")
                .contains("boardRimBreath")
                .contains("panelRimBreath")
                .contains("headerRimBreath")
                .contains("animation: headerRimBreath 4.5s ease-in-out infinite; user-select: none")
                .contains("0%, 100% { border-bottom-color: rgba(153, 111, 49, 0.38); }")
                .contains("headerRimBreath 4.5s ease-in-out infinite; user-select: none; -webkit-user-select: none")
                .contains("-webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("-webkit-touch-callout: none; -webkit-user-drag: none; cursor: default")
                .contains("legendFadeBreath")
                .contains("#legend { display: flex; gap: 14px; justify-content: center; flex-wrap: wrap;")
                .contains("color: #b09a72; pointer-events: none; text-wrap: pretty;")
                .contains("user-select: none; -webkit-user-select: none; -webkit-touch-callout: none;")
                .contains("user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("rgba(16, 11, 8, .50)")
                .contains("rgba(16, 11, 8, .88)")
                .contains("color: #b09a72")
                .contains("none; -webkit-touch-callout: none; line-height: 1.45")
                .contains("line-height: 1.45; -webkit-user-drag: none")
                .contains(".info b { color: #f2ead8; font-weight: 600;")
                .contains("#f2ead8; cursor: default; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none")
                .contains("#f2ead8; cursor: default; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; -webkit-user-drag: none")
                .contains("#stats span { color: #b09a72;")
                .contains("cursor: default; user-select: none; -webkit-user-select: none; -webkit-touch-callout: none; margin-top: 8px")
                .contains("callout: none; margin-top: 8px; -webkit-user-drag: none")
                .contains("exportsRimBreath")
                .contains("gap: 8px; align-items: center; -webkit-user-drag: none")
                .contains("border-color: rgba(153, 111, 49, 0.85); color: #f2ead8")
                .contains("ghost: \"#e8e0d4\"")
                .contains("radial-gradient(circle at 45% 40%, #e8e0d4 28%, #6a6258)")
                .contains("ghostDisc")
                .contains("ageFade")
                .contains("0.35 + 0.65")
                .contains("0.55 + 0.45")
                .contains("\"ribbon\"")
                .contains("g.globalAlpha = 0.26")
                .contains("0.32, true")
                .contains("GHOST_BREATH_MS")
                .contains("0.18 + 0.08")
                .contains("WAYPOINT_BREATH_MS")
                .contains("const coinInk = waypointInk(w, th, tw, got)")
                .contains("g.fillStyle = coinInk")
                .contains("g.strokeStyle = coinInk")
                .contains("0.14 + 0.05")
                .contains("0.10 + 0.10")
                .contains("0.72 + 0.28")
                .contains("PATH_HEAD_BREATH_MS")
                .contains("0.5 + 0.05")
                .contains("0.22 + 0.10")
                .contains("0.65 + 0.15")
                .contains("SANCTUARY_BREATH_MS")
                .contains("const safeInk = sanctuaryInk(p, th, tw)")
                .contains("marker(g, geom, p, safeInk, 0.32)")
                .contains("0.48 + 0.05")
                .contains("MARKER_BREATH_MS")
                .contains("0.16 + 0.12 * wave")
                .contains("0.55 + 0.20 * wave")
                .contains("HOTSPOT_BREATH_MS")
                .contains("0.28 + 0.04")
                .contains("FIELD_BREATH_MS")
                .contains("\"#4a2210\"")
                .contains("\"#f2d8a0\"")
                .contains("color:#af8441")
                .contains("width:16px;height:10px;background:${c};")
                .contains("box-shadow:0 0 0 1.5px rgba(242, 234, 216, .28)")
                .contains("0.88 + 0.24")
                .contains("0.85 + 0.30")
                .contains("LENS_BREATH_MS")
                .contains("LENS_COLORS = [\"#e5484d\", \"#f2c94c\", \"#8aaa50\"]")
                .contains("background:${i === 0 ? \"#bc4041\" : i === 1 ? \"#c6a441\" : \"#758c44\"};margin-right:4px;")
                .contains("box-shadow:0 0 0 1.5px rgba(242, 234, 216, .28)\"></span>${label}")
                .contains("color:#758c44\">${escapeHtml(f.predictedGeneratorId)}")
                .contains("color:#c49425\">${escapeHtml(f.predictedGeneratorId)}")
                .contains("color:#758c44\">${s.placements.length} sanctuaries")
                .contains("color:#9f6544\">${cp}")
                .contains("color:#bc4041'>not optimal")
                .contains("0.88 + 0.24 * lensWave")
                .contains("0.85 + 0.30 * lensWave")
                .contains("EXPANSION_BREATH_MS")
                .contains("0.16 * (0.88 + 0.24")
                .contains("0.26 * (0.85 + 0.30")
                .contains("0.45 * (0.88 + 0.24")
                .contains("RACE_BREATH_MS")
                .contains("0.13 * (0.88 + 0.24")
                .contains("0.20 * (0.85 + 0.30")
                .contains("0.4 * (0.88 + 0.24")
                .contains("g.globalAlpha = 0.20")
                .contains("CUTS_BREATH_MS")
                .contains("const endInk = deadendInk(p, th, tw)")
                .contains("g.fillStyle = endInk")
                .contains("g.strokeStyle = endInk")
                .contains("const cutInk = chokeInk(tr, tc, th, tw)")
                .contains("g.fillStyle = cutInk")
                .contains("g.strokeStyle = cutInk")
                .contains("radial-gradient(circle at 45% 40%, #c07850 28%, #6a4030)")
                .contains("0.18 + 0.05")
                .contains("PLAYER_BREATH_MS")
                .contains("PLAYER_COLORS = [\"#f5c14a\", \"#e88868\", \"#e8a060\", \"#b8a058\"]")
                .contains("function walker")
                .contains("walkHead(scene.hardest.path, 1)")
                .contains("paintWalk(g, geom, scene.hardest.path, \"#c6a441\", 1, 0.75, \"ribbon\"")
                .contains("hardestTileInk(2 * hardTip.row + 1, 2 * hardTip.col + 1, th, tw)\n"
                        + "          : \"#c6a441\")")
                .contains("walkHead(scene.tourPath, 1)")
                .contains("paintWalk(g, geom, scene.tourPath, \"#af9158\"")
                .contains("tourTileInk(2 * tourTip.row + 1, 2 * tourTip.col + 1, th, tw)\n"
                        + "          : \"#af9158\")")
                .contains("endpoint(g, geom, {row: 0, col: 0}")
                .contains("VICTORY_BREATH_MS")
                .contains("0.85 + 0.08")
                .contains("emptyWordmarkGoldGlow(0.04 + 0.03 * wave)")
                .contains("data-key=\"path\"").contains("data-key=\"floor\"")
                .contains("data-key=\"fog\"")
                .contains("data-key=\"sanctuary\"")
                .contains("data-key=\"lens\"")
                .contains("data-key=\"hardest\"")
                .contains("radial-gradient(circle at 45% 40%, #f2c94c 28%, #8a6820)")
                .contains("data-key=\"tour\"")
                .contains("data-key=\"deadend\"")
                .contains("#legend [data-key=\"choke\"] i, #legend [data-key=\"deadend\"] i")
                .contains("#legend [data-key=\"path\"] i")
                .contains("#legend [data-key=\"path\"] i, #legend [data-key=\"race\"] i")
                .contains("#legend [data-key=\"lens\"] i")
                .contains("#legend [data-key=\"lens\"] i, #legend [data-key=\"floor\"] i")
                .contains("radial-gradient(circle at 45% 40%, #e5484d 28%, #6a2024)")
                .contains("radial-gradient(circle at 45% 40%, #8aaa50 28%, #4e6a28)")
                .contains("#legend [data-key=\"wall\"] i, #legend [data-key=\"fog\"] i")
                .contains("#legend [data-key=\"tour\"] i")
                .contains("radial-gradient(circle at 45% 40%, #d4b06a 28%, #6a5428)")
                .contains("#legend [data-key=\"hotspot\"] i")
                .contains("radial-gradient(circle at 45% 40%, rgba(229,72,77,.5) 28%, rgba(106,32,36,.5))")
                .contains("rgba(229, 72, 77, .35)")
                .contains("sanctuary: !!(snap.sanctuaries")
                .contains("lens: !!snap.lens")
                .contains("hardest: !!(snap.hardest")
                .contains("tour: !!(snap.tourPath && snap.tourPath.length)")
                .contains("data-key=\"race\"")
                .contains("radial-gradient(circle at 45% 40%, #8fb8ff 28%, #3a5888)")
                .contains("radial-gradient(circle at 45% 40%, #f0b429 28%, #8a6018)")
                .contains("color: \"#8fb8ff\"")
                .contains(">arena</span>")
                .contains("data-key=\"player\"")
                .contains("radial-gradient(circle at 45% 40%, #f5c14a 28%, #8a6418)")
                .contains("radial-gradient(circle at 45% 40%, #e88868 28%, #8a3828)")
                .contains("radial-gradient(circle at 45% 40%, #e8a060 28%, #8a5020)")
                .contains("radial-gradient(circle at 45% 40%, #b8a058 28%, #6a5420)")
                .contains(">players</span>")
                .contains("race: !!(snap.race && snap.race.lanes && snap.race.lanes.length)")
                .contains("deadend: !!(snap.analysis && snap.analysis.deadEnds")
                .contains("rgba(245, 193, 74, .35)")
                .contains("rgba(242,234,216,.06)")
                .contains("rgba(242, 234, 216, .28)")
                .contains("Authorization").contains("text/plain").contains("id=\"ascii\"")
                .contains("/plugins").contains("id=\"pluginBox\"")
                .contains("id=\"lbGen\"").contains("generator=")
                .contains("view.walks").contains("#session=").contains("#daily")
                .contains("id=\"braid\"").contains("/topic/plugins/failures")
                .contains("integrity=")
                .contains("fog walk ended")
                .contains("every solver failed")
                .contains("aged out of the cache")
                .contains("classifier is warming")
                .contains("this session already finished")
                .contains("that session is gone")
                .contains("too many mazes are already alive")
                .contains("too many mazes are already tracked")
                .contains("session-capacity").contains("agent-capacity")
                .contains("maze-capacity").contains("tour-capacity")
                .contains("too many sessions are already open")
                .contains("too many fog walks are already open")
                .contains("too many mazes are already cached")
                .contains("too many waypoint hunts are already seated")
                .contains("permalink maze aged out —")
                .contains("that maze is gone")
                .contains("that fog walk is gone")
                .contains("solver-budget")
                .contains("this solver spent its node budget")
                .contains("spectating is read-only")
                .doesNotContain("positions[state.session.primary]")
                .doesNotContain("move(state.session.primary")
                .doesNotContain("move(state.seat || state.session.primary");
        assertThat(html).contains(
                "#compareBox table { width: 100%; margin-top: 8px; border-collapse: collapse; -webkit-user-drag: none")
                .contains("#pluginBox b { color: #f2ead8; -webkit-user-drag: none")
                .contains("#pluginBox .rank { color: #b09a72; -webkit-user-drag: none")
                .contains("#compareBox .best { color: #c49425; font-weight: 700; -webkit-user-drag: none")
                .contains("#compareBox .hint { color: #b09a72; -webkit-user-drag: none");
    }
}
