// SPDX-License-Identifier: MIT

package com.daedalus.server;

import com.daedalus.server.config.ProdSecurityConfig;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.client.RestTestClient;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Pins that the static web UI is actually served. The page is plain static
 * content under {@code resources/static}, which Boot serves by convention —
 * and conventions are exactly what starter upgrades silently change.
 *
 * <p><b>This is a boot-and-serve contract, not a leftover-state mirror.</b>
 * Leftover-state and feature regressions belong in {@code sweep/}:
 * {@code api-sweep.py} runs in CI; {@code ui-sweep.js} is the local Playwright
 * pass. Do not add {@code indexOf("async function …")} body pins here.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
class WebUiSmokeTest {

    @LocalServerPort
    private int port;

    @Test
    void theWebUiIsServedAtTheRoot() {
        RestTestClient client = RestTestClient.bindToServer()
                .baseUrl("http://localhost:" + port).build();
        byte[] body = client.get().uri("/index.html").exchange()
                .expectStatus().isOk()
                .expectBody().returnResult().getResponseBody();
        assertThat(body).isNotNull();
        StringBuilder js = new StringBuilder();
        for (String path : ProdSecurityConfig.STATIC_SCRIPTS) {
            byte[] bytes = client.get().uri(path).exchange()
                    .expectStatus().isOk()
                    .expectBody().returnResult().getResponseBody();
            assertThat(bytes).as("nothing served at %s", path).isNotNull();
            js.append(new String(bytes));
        }
        String html = new String(body) + js;
        // Public surface, not leftover names. Paths, ids, permalink kinds, and
        // refuse copy are what a player or operator sees. Function names belong
        // in sweep/ — a rename there must not fail this boot-and-serve test.
        assertThat(html).contains("DAEDALUS").contains("id=\"gate\"").contains("id=\"gateWell\"")
                .contains("id=\"gateExploreCmd\"").contains("id=\"home\"")
                .contains("gate-brand").contains("gate-veil").contains("Other hosts")
                .contains("name=\"theme-color\" content=\"#0c0908\"")
                .contains("name=\"msapplication-TileColor\" content=\"#0c0908\"")
                .contains("name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\"")
                .contains("name=\"color-scheme\" content=\"dark\"")
                .contains("rel=\"icon\" type=\"image/svg+xml\"")
                .contains("fill='%230c0908'")
                .contains("stroke='%23b88538'")
                .contains("rel=\"mask-icon\" color=\"#b88538\"")
                .contains("fill-rule='evenodd' d='M0 0h32v32H0zM4 4h24v24H4z'")
                .contains("color: #f2ead8")
                .contains("header h1 button")
                .contains("header .tag { color: #b09a72")
                .contains("rgba(22, 18, 14, .88)")
                .contains("#gate { position: fixed; inset: 0; z-index: 20; overflow: auto; overscroll-behavior: none;")
                .contains("html, body { min-height: 100%; color-scheme: dark; background-color: #0c0908;")
                .contains("overscroll-behavior: none;")
                .contains("-webkit-tap-highlight-color: rgba(184, 133, 56, 0.25);")
                .contains("::-webkit-scrollbar { width: 8px; height: 8px; }")
                .contains("::-webkit-scrollbar-thumb { background: rgba(184, 133, 56, 0.45); border-radius: 4px; }")
                .contains("::-webkit-scrollbar-thumb:hover { background: rgba(184, 133, 56, 0.65); }")
                .contains("::-webkit-scrollbar-thumb:active { background: rgba(184, 133, 56, 0.85); }")
                .contains("::-webkit-scrollbar-track { background: transparent; }")
                .contains("::-webkit-scrollbar-corner { background: transparent; }")
                .contains("::-webkit-scrollbar-button { display: none; width: 0; height: 0; }")
                .contains("::selection { background: rgba(184, 133, 56, 0.35); color: #f2ead8; }")
                .contains("::-moz-selection { background: rgba(184, 133, 56, 0.35); color: #f2ead8; }")
                .contains("::target-text { background: rgba(184, 133, 56, 0.35); color: #f2ead8; }")
                .contains("::search-text { background: rgba(184, 133, 56, 0.35); color: #f2ead8; }")
                .contains("::search-text:current { background: rgba(184, 133, 56, 0.55); color: #f2ead8; }")
                .contains("@media print {")
                .contains("print-color-adjust: exact; -webkit-print-color-adjust: exact;")
                .contains("@media (forced-colors: active) {")
                .contains("html, body, #gate, #stage, canvas { forced-color-adjust: none; }")
                .contains("::spelling-error { text-decoration: underline wavy rgba(184, 133, 56, 0.85); }")
                .contains("::grammar-error { text-decoration: underline wavy rgba(176, 154, 114, 0.85); }")
                .contains("#gate article h3")
                .contains("letter-spacing: .04em; color: #f2ead8")
                .contains("#gate .lede { color: #b09a72")
                .contains("#gate article p { margin: 0; color: #b09a72")
                .contains("animation: gateRise .55s ease both, panelRimBreath 4.5s ease-in-out infinite")
                .contains("#gate pre { margin: 0; padding: 8px; background: #16120e; color: #d4c4a8;")
                .contains("font: 11px/1.45 ui-monospace, monospace; overflow: auto")
                .contains("gateBreath").contains("gateVeil")
                .contains("rgba(245, 193, 74, .05)")
                .contains("rgba(184, 133, 56, 0.28)")
                .contains("/api/v1").contains("/ws")
                .contains("/auth/login").contains("id=\"login\"").contains("id=\"fog\"")
                .contains("id=\"legend\"").contains("id=\"labMetric\"").contains("class=\"rail\"")
                .contains("id=\"compareBox\"")
                .contains("#compareBox tr.solver-row:hover { background: #1a1610")
                .contains("#compareBox tr.pinned { background: #1a1610")
                .contains("#compareBox { max-height: 22vh")
                .contains("scrollbar-color: rgba(184, 133, 56, 0.45) transparent")
                .contains("color: #f2ead8")
                .contains("#compareBox th { text-align: left; color: #b09a72")
                .contains("#compareBox td { padding: 2px 8px; border-bottom: 1px solid rgba(184, 133, 56, 0.28)")
                .contains("#compareBox .hint { color: #b09a72")
                .contains("#compareBox > div { border-top: 1px solid rgba(184, 133, 56, 0.28); padding-top: 6px;")
                .contains("#compareBox .best { color: #f0b429")
                .contains("color:#f0b429\">${escapeHtml(w.id)}</b> wins the arena")
                .contains("color:#f0b429\">${escapeHtml(w.id)}</b> wins by default")
                .contains("id=\"genInfo\"").contains("id=\"asciiOut\"")
                .contains("#asciiOut { margin: 10px 0 0; padding: 8px; background: #16120e;")
                .contains("font: 11px/1.2 ui-monospace, monospace; overflow: auto; overscroll-behavior: none;")
                .contains("animation: panelRimBreath 4.5s ease-in-out infinite; }")
                .contains(".exports button, .exports a, #asciiOut, #gate pre, .info, #stats, details,")
                .contains("#compareBox > div, kbd, summary::after, #log, #lb, #pluginBox, #campaignBox,")
                .contains("#tourBox, #labOut, #compareBox, #status {")
                .contains("#campaignBox { padding: 8px; background: #16120e;")
                .contains("#tourBox { padding: 8px; background: #16120e;")
                .contains("#labOut { padding: 8px; background: #16120e;")
                .contains("#compareBox { max-height: 22vh; overflow: auto; min-width: 0;")
                .contains("animation: chevronBreath 4.5s ease-in-out infinite; }")
                .contains("animation: infoRimBreath 4.5s ease-in-out infinite; }")
                .contains("animation: statsRimBreath 4.5s ease-in-out infinite; }")
                .contains("color: #d4c4a8;")
                .contains("max-height: 22vh; color: #d4c4a8")
                .contains("#asciiOut .rock { color: #8c764e")
                .contains("#asciiOut .gate { color: #3ee08f")
                .contains("#asciiOut .exit { color: #ff5a5f")
                .contains("replace(/#/g, \"<span class=\\\"rock\\\">#</span>\")")
                .contains("replace(/S/g, \"<span class=\\\"gate\\\">S</span>\")")
                .contains("replace(/G/g, \"<span class=\\\"exit\\\">G</span>\")")
                .contains("scrollbar-width: thin; scrollbar-color: rgba(184, 133, 56, 0.45) transparent; }")
                .contains("class=\"exports\"").contains("EXPORT_RESERVE")
                .contains("canvas { background: transparent; display: block;")
                .contains("image-rendering: crisp-edges; image-rendering: pixelated;")
                .contains("id=\"pngExport\" class=\"hint\" href=\"#\" download=\"maze.png\"")
                .contains(".exports a:focus-visible { outline: 2px solid rgba(184, 133, 56, 0.85); outline-offset: 1px; }")
                .contains("style=\"display:none\">download as PNG")
                .contains("color: #b09a72")
                .contains("background: rgba(16, 11, 8, .78)")
                .contains("Pick a generator and press Generate")
                .contains("Bahnschrift")
                .contains("radial-gradient(80% 70% at 50% 45%")
                .contains("inset 0 0 48px rgba(0, 0, 0, .35)")
                .contains("rgba(184, 133, 56")
                .contains("0 0 18px rgba(62, 224, 143")
                .contains("animation: gateBreath 4.5s ease-in-out infinite")
                .contains("board-panel")
                .contains(".board-panel { display: flex; flex-direction: column; min-height: calc(100vh - 88px);")
                .contains("background: #16120e;")
                .contains("0 0 0 1px rgba(16, 11, 8, 0.85)")
                .contains("inset 3px 0 0 rgba(184, 133, 56")
                .contains("inset 3px 0 0 rgba(184, 133, 56, 0.55)")
                .contains("0 0 12px rgba(184, 133, 56")
                .contains("outline: 2px solid rgba(184, 133, 56")
                .contains("border: 1px solid rgba(184, 133, 56, 0.28)")
                .contains("border: 1px solid rgba(184, 133, 56, 0.32)")
                .contains("border: 1px solid rgba(184, 133, 56, 0.36)")
                .contains("button.accent")
                .contains("border-color: var(--gold)")
                .contains("backdrop-filter")
                .contains("floorWarm")
                .contains("g.fillStyle = \"#f2ead8\"")
                .contains("wallWarm")
                .contains("0.22 * edge")
                .contains("floor: \"#40403c\"")
                .contains("mixHex(COLORS.floor, COLORS.floorWarm, 0.28)")
                .contains("background:#484339")
                .contains("mixHex(warm, COLORS.floorDim, 0.22 * edge)")
                .contains("mixHex(hi, COLORS.floorDim, 0.22 * edge)")
                .contains("floorDim: \"#2a2218\"")
                .contains("mixHex(COLORS.floorHi, COLORS.floorWarm, lamp * 0.28)")
                .contains("floorHi: \"#765834\"")
                .contains("wallHi: \"#4a3824\"")
                .contains("mixHex(COLORS.wallHi, COLORS.wallWarm, 0.28)")
                .contains("paintWallHi(g, geom, r, c, mixHex(COLORS.wallHi, COLORS.wallWarm, 0.28))")
                .contains("wall: \"#120e0c\"")
                .contains("mixHex(COLORS.wall, COLORS.wallWarm, 0.28)")
                .contains("background:#19140f")
                .contains("scene.fog")
                .contains("COLORS.unseen")
                .contains("unseen: \"#0c0908\"")
                .contains("<span data-key=\"fog\"><i style=\"background:#0c0908\"></i>unseen (fog)</span>")
                .contains(": mixHex(COLORS.wall, COLORS.wallWarm, 0.28)")
                .contains("mixHex(warmWall, COLORS.unseen, 0.28 * edge)")
                .contains("FOG_FRONTIER")
                .contains("fogFrontier")
                .contains("FOG_FRONTIER_BREATH_MS")
                .contains("0.92 + 0.16")
                .contains("core + geom.cell * (0.18 + 0.05")
                .contains("geom.cell * (0.28 + 0.04")
                .contains("ENDPOINT_BREATH_MS")
                .contains("0.55 + 0.06")
                .contains("shadowBlur")
                .contains("EMPTY_BREATH_MS")
                .contains("mixHex(\"#16120e\", \"#1a1510\", wave)")
                .contains("voidWash.addColorStop(1, COLORS.unseen)")
                .contains("0.36 + 0.10")
                .contains("0.22 + 0.08")
                .contains("0.72 + 0.18")
                .contains("0.55 + 0.20")
                .contains("0.08 + 0.04")
                .contains("0.04 + 0.03")
                .contains("prefers-reduced-motion")
                .contains("stageRimBreath")
                .contains("#1a1510 0%")
                .contains("#16120e 0%")
                .contains("radial-gradient(1200px 700px at 50% -10%, #16120e 0%")
                .contains("font: 14px/1.5 system-ui, \"Segoe UI\", sans-serif")
                .doesNotContain("color: var(--text);\r\n         font: 14px/1.5")
                .contains("#1a1510 0%")
                .contains("--void: #0c0908")
                .contains("--bg: #0c0908")
                .contains("--panel: #16120e")
                .doesNotContain("--panel: #10151b")
                .doesNotContain("--accent2: #7eb6ff")
                .contains("--accent2: #8fb8ff")
                .doesNotContain("--line: #1e2832")
                .contains("--line: #2a2218")
                .contains(".panel h2 { margin: 0 0 8px; font-size: 11px; text-transform: uppercase;")
                .contains("letter-spacing: .14em; color: #b09a72; font-weight: 600; }")
                .contains(".hint { font-size: 11px; color: #b09a72; margin-top: 10px; }")
                .contains("#log { height: 240px; overflow-y: auto; overscroll-behavior: none; font: 12px/1.6 ui-monospace, monospace;")
                .contains("color: #f2ead8;")
                .contains("#log .t { color: #b09a72; margin-right: 6px; }")
                .contains("#log .solver { color: #d4a04c; }")
                .contains("#log div { border-bottom: 1px solid rgba(184, 133, 56, 0.28); padding: 2px 0; }")
                .contains("#labOut, #tourBox, #campaignBox { color: #f2ead8; }")
                .contains("#pluginBox { color: #b09a72; padding: 8px; background: #16120e;")
                .contains("#pluginBox b { color: #f2ead8; }")
                .contains("#tourBox th { text-align: left; color: #b09a72; font-weight: 600;")
                .contains("#tourBox td { padding: 2px 8px; border-bottom: 1px solid rgba(184, 133, 56, 0.28); }")
                .contains("#tourBox a { color: #d4a04c; }")
                .contains("#tourBox a:focus-visible { outline: 2px solid rgba(184, 133, 56, 0.85); outline-offset: 1px; }")
                .contains("#labOut th { text-align: left; color: #b09a72; font-weight: 600;")
                .contains("#labOut td { padding: 2px 8px; border-bottom: 1px solid rgba(184, 133, 56, 0.28); }")
                .contains("#pluginBox .rank { color: #b09a72; }")
                .contains("#pluginBox div { border-bottom: 1px solid rgba(184, 133, 56, 0.28); padding: 2px 0; }")
                .contains("#campaignBox div { border-bottom: 1px solid rgba(184, 133, 56, 0.28); }")
                .contains("#campaignBox a:focus-visible { outline: 2px solid rgba(184, 133, 56, 0.85); outline-offset: 1px; }")
                .contains("const LAB_SERIES = \"#d4a04c\"")
                .contains("stroke=\"#8c764e\" stroke-width=\"2\"")
                .contains("stroke=\"#16120e\" stroke-width=\"2\"")
                .contains("stroke=\"rgba(184, 133, 56, 0.28)\"")
                .contains("fill=\"#b09a72\" font-size=\"9\"")
                .contains("#lb { font: 12px/1.9 ui-monospace, monospace; color: #f2ead8;")
                .contains("#lb div { border-bottom: 1px solid rgba(184, 133, 56, 0.28); padding: 2px 0; }")
                .contains("#lb span { color: #b09a72; }")
                .contains("#lb .rank { display: inline-block; width: 18px; color: #b09a72; }")
                .contains("#lb b { color: #f2ead8; }")
                .contains("${active ? \"background:#1a1610;\" : \"\"}")
                .contains("color:${done ? \"#4cc38a\" : \"#d4a04c\"}")
                .contains("details { margin-top: 10px; border-top: 1px solid rgba(184, 133, 56, 0.28); padding-top: 6px;")
                .contains("letter-spacing: .12em; color: #b09a72; margin: 4px 0 2px;")
                .contains("summary::after { content: \" ▸\"; color: rgba(184, 133, 56, 0.55);")
                .contains("kbd { background: #16120e; border: 1px solid rgba(184, 133, 56, 0.28); border-radius: 3px;")
                .contains("padding: 0 4px; font-size: 11px; color: #b09a72;")
                .contains("background: rgba(12, 9, 8, 0.92)")
                .contains("boardRimBreath")
                .contains("panelRimBreath")
                .contains("headerRimBreath")
                .contains("legendFadeBreath")
                .contains("rgba(16, 11, 8, .50)")
                .contains("rgba(16, 11, 8, .88)")
                .contains("color: #b09a72")
                .contains(".info { font-size: 11px; color: #b09a72;")
                .contains(".info b { color: #f2ead8; font-weight: 600; }")
                .contains("#stats { font: 12px/1.7 ui-monospace, monospace; color: #f2ead8;")
                .contains("#stats span { color: #b09a72; }")
                .contains("#status { font-size: 12px; color: #b09a72; margin-top: 8px;")
                .contains("exportsRimBreath")
                .contains("border-color: rgba(184, 133, 56, 0.85); color: #f2ead8")
                .contains("ghost: \"#e8e0d4\"")
                .contains("background:#e8e0d4;border-radius:50%;opacity:.6")
                .contains("ghostDisc")
                .contains("ageFade")
                .contains("0.35 + 0.65")
                .contains("0.55 + 0.45")
                .contains("\"ribbon\"")
                .contains("g.globalAlpha = 0.26")
                .contains("0.32, true")
                .contains("GHOST_BREATH_MS")
                .contains("0.18 + 0.08")
                .contains("WAYPOINT_BREATH_MS")
                .contains("g.fillStyle = \"#8aaa50\"")
                .contains("g.strokeStyle = \"#8aaa50\"")
                .contains("0.14 + 0.05")
                .contains("0.10 + 0.10")
                .contains("0.72 + 0.28")
                .contains("PATH_HEAD_BREATH_MS")
                .contains("0.5 + 0.05")
                .contains("0.22 + 0.10")
                .contains("0.65 + 0.15")
                .contains("SANCTUARY_BREATH_MS")
                .contains("marker(g, geom, p, \"#8aaa50\", 0.32)")
                .contains("0.48 + 0.05")
                .contains("MARKER_BREATH_MS")
                .contains("0.16 + 0.12 * wave")
                .contains("0.55 + 0.20 * wave")
                .contains("HOTSPOT_BREATH_MS")
                .contains("0.28 + 0.04")
                .contains("FIELD_BREATH_MS")
                .contains("\"#4a2210\"")
                .contains("\"#f2d8a0\"")
                .contains("color:#d4a04c")
                .contains("width:16px;height:10px;background:${c};")
                .contains("box-shadow:0 0 0 1.5px rgba(242, 234, 216, .28)")
                .contains("0.88 + 0.24")
                .contains("0.85 + 0.30")
                .contains("LENS_BREATH_MS")
                .contains("LENS_COLORS = [\"#e5484d\", \"#f2c94c\", \"#8aaa50\"]")
                .contains("background:${LENS_COLORS[i]};margin-right:4px;")
                .contains("box-shadow:0 0 0 1.5px rgba(242, 234, 216, .28)\"></span>${label}")
                .contains("color:#8aaa50\">${escapeHtml(f.predictedGeneratorId)}")
                .contains("color:#8aaa50\">${s.placements.length} sanctuaries")
                .contains("0.88 + 0.24 * lensWave")
                .contains("0.85 + 0.30 * lensWave")
                .contains("EXPANSION_BREATH_MS")
                .contains("0.16 * (0.88 + 0.24")
                .contains("0.26 * (0.85 + 0.30")
                .contains("0.45 * (0.88 + 0.24")
                .contains("RACE_BREATH_MS")
                .contains("0.13 * (0.88 + 0.24")
                .contains("0.20 * (0.85 + 0.30")
                .contains("0.4 * (0.88 + 0.24")
                .contains("g.globalAlpha = 0.20")
                .contains("CUTS_BREATH_MS")
                .contains("g.fillStyle = \"#c8a878\"")
                .contains("g.strokeStyle = \"#c8a878\"")
                .contains("g.fillStyle = \"#c07850\"")
                .contains("g.strokeStyle = \"#c07850\"")
                .contains("background:#c07850")
                .contains("0.18 + 0.05")
                .contains("PLAYER_BREATH_MS")
                .contains("PLAYER_COLORS = [\"#f5c14a\", \"#e88868\", \"#e8a060\", \"#b8a058\"]")
                .contains("function walker")
                .contains("walkHead(scene.hardest.path, 1)")
                .contains("walkHead(scene.tourPath, 1)")
                .contains("paintWalk(g, geom, scene.tourPath, \"#d4b06a\"")
                .contains("walkHead(scene.tourPath, 1), \"#d4b06a\"")
                .contains("endpoint(g, geom, {row: 0, col: 0}")
                .contains("VICTORY_BREATH_MS")
                .contains("0.85 + 0.08")
                .contains("rgba(245, 193, 74, \" + (0.04 + 0.03")
                .contains("data-key=\"path\"").contains("data-key=\"floor\"")
                .contains("data-key=\"fog\"")
                .contains("data-key=\"sanctuary\"")
                .contains("data-key=\"lens\"")
                .contains("data-key=\"hardest\"")
                .contains("data-key=\"tour\"")
                .contains("data-key=\"deadend\"")
                .contains("#legend [data-key=\"choke\"] i, #legend [data-key=\"deadend\"] i")
                .contains("#legend [data-key=\"path\"] i")
                .contains("#legend [data-key=\"path\"] i, #legend [data-key=\"race\"] i")
                .contains("#legend [data-key=\"lens\"] i")
                .contains("#legend [data-key=\"lens\"] i, #legend [data-key=\"floor\"] i")
                .contains("#legend [data-key=\"wall\"] i, #legend [data-key=\"fog\"] i")
                .contains("#legend [data-key=\"tour\"] i")
                .contains("background:#d4b06a")
                .contains("#legend [data-key=\"hotspot\"] i")
                .contains("rgba(229, 72, 77, .35)")
                .contains("sanctuary: !!(snap.sanctuaries")
                .contains("lens: !!snap.lens")
                .contains("hardest: !!(snap.hardest")
                .contains("tour: !!(snap.tourPath && snap.tourPath.length)")
                .contains("data-key=\"race\"")
                .contains("background:#8fb8ff")
                .contains("color: \"#8fb8ff\"")
                .contains(">arena</span>")
                .contains("data-key=\"player\"")
                .contains("background:#e88868;border-radius:50%")
                .contains("background:#e8a060;border-radius:50%")
                .contains("background:#b8a058;border-radius:50%;margin-right:0")
                .contains(">players</span>")
                .contains("race: !!(snap.race && snap.race.lanes && snap.race.lanes.length)")
                .contains("deadend: !!(snap.analysis && snap.analysis.deadEnds")
                .contains("rgba(245, 193, 74, .35)")
                .contains("rgba(242,234,216,.06)")
                .contains("rgba(242, 234, 216, .28)")
                .contains("Authorization").contains("text/plain").contains("id=\"ascii\"")
                .contains("/plugins").contains("id=\"pluginBox\"")
                .contains("id=\"lbGen\"").contains("generator=")
                .contains("view.walks").contains("#session=").contains("#daily")
                .contains("id=\"braid\"").contains("/topic/plugins/failures")
                .contains("integrity=")
                .contains("fog walk ended")
                .contains("every solver failed")
                .contains("aged out of the cache")
                .contains("classifier is warming")
                .contains("this session already finished")
                .contains("that session is gone")
                .contains("too many mazes are already alive")
                .contains("too many mazes are already tracked")
                .contains("session-capacity").contains("agent-capacity")
                .contains("maze-capacity").contains("tour-capacity")
                .contains("too many sessions are already open")
                .contains("too many fog walks are already open")
                .contains("too many mazes are already cached")
                .contains("too many waypoint hunts are already seated")
                .contains("permalink maze aged out —")
                .contains("that maze is gone")
                .contains("that fog walk is gone")
                .contains("solver-budget")
                .contains("this solver spent its node budget")
                .contains("spectating is read-only")
                .doesNotContain("positions[state.session.primary]")
                .doesNotContain("move(state.session.primary")
                .doesNotContain("move(state.seat || state.session.primary");
    }
}
