#!/usr/bin/env python3
"""
Generate a basic Daedalus Java plugin skeleton.
"""

import sys
from pathlib import Path

TEMPLATE = '''package com.example.{package_name};

import com.daedalus.plugin.*;
import com.daedalus.engine.generators.*;
import com.daedalus.model.AlgorithmDescriptor;

public class {class_name} extends AbstractPlugin {{

    @Override
    public PluginManifest manifest() {{
        return new PluginManifest(
            "{plugin_id}",
            "{display_name}",
            "1.0.0",
            "Your Name",
            "{description}"
        );
    }}

    @Override
    public void registerAlgorithms(PluginContext ctx) {{
        ctx.generators().register(new {generator_class}());
        // Add more generators here
    }}

    // Example custom generator
    static class {generator_class} extends AbstractMazeGenerator {{
        @Override public String id() {{ return "{generator_id}"; }}
        @Override public String displayName() {{ return "{display_name}"; }}

        @Override
        public AlgorithmDescriptor descriptor() {{
            return new AlgorithmDescriptor(
                id(), displayName(), "generator",
                "O(n) time",
                "Custom bias description",
                "Generated by Daedalus Python plugin tool"
            );
        }}

        @Override
        public MazeGrid generate(int rows, int cols, long seed, MazeStats stats) {{
            // TODO: Implement your generation logic
            MazeGrid grid = new MazeGrid(rows, cols);
            // ... your algorithm here
            stats.finish(true);
            return grid;
        }}
    }}
}}
'''

def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_plugin.py <PluginName>")
        sys.exit(1)

    name = sys.argv[1]
    class_name = name if name.endswith("Plugin") else name + "Plugin"
    package_name = name.lower().replace("plugin", "")
    generator_class = name.replace("Plugin", "Generator")
    generator_id = package_name + "-generator"
    display_name = name.replace("Plugin", "").replace("_", " ").title()

    content = TEMPLATE.format(
        package_name=package_name,
        class_name=class_name,
        plugin_id=package_name,
        display_name=display_name,
        description=f"Custom {display_name} plugin for Daedalus",
        generator_class=generator_class,
        generator_id=generator_id
    )

    out_dir = Path(f"plugins/{package_name}")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{class_name}.java"
    out_file.write_text(content)

    print(f"✅ Plugin generated: {out_file}")
    print(f"   Package: com.example.{package_name}")
    print(f"   Generator ID: {generator_id}")

if __name__ == "__main__":
    main()